version: "3.8"
services:
  web-server:
    image: tomcat:9.0.62-jre8-temurin
    environment:
      JPDA_ADDRESS: 8000
      JPDA_TRANSPORT: dt_socket
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
    # mem_limit: 2GB
    volumes:
      #server config files
      - C:\tomcat\conf\server.xml:/usr/local/tomcat/conf/server.xml
      - C:\tomcat\conf\context.xml:/usr/local/tomcat/conf/context.xml
      - C:\tomcat\conf\tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml      
      #server deploy path
      - webapps_folder:/usr/local/tomcat/webapps
      #server log and deploy log
      - logs_folder:/usr/local/tomcat/logs
      
      # Set CLASSPATH to get shared/libs
      - C:\tomcat\bin\setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - shared_libs:/shared/libs
    ports:
      - "8080:8080"
      - "8000:8000"
    #network config to get VPN connection
    networks:
      - my-network

      
networks:
  my-network:
    driver: bridge

volumes:
  shared_libs:
    driver: local
    driver_opts:
      type: none
      device: C:\shared\libs
      o: bind
  webapps_folder:
    driver: local
    driver_opts:
      type: none
      device: C:\tomcat\webapps
      o: bind
  logs_folder:
    driver: local
    driver_opts:
      type: none
      device: C:\tomcat\logs
      o: bind