version: '3.8'
services:
  postgres_db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: service_db
    volumes:
      - /postgresql:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U root -d service_db
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  migrate:
    image: migrate/migrate
    depends_on:
      postgres_db:
        condition: service_healthy
    volumes:
      - ./database:/database
    command:
      [ "-path", "/database", "-database",  "postgres://root:root@postgres_db:5432/service_db?sslmode=disable", "up" ]
volumes:
  pgdata: